"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_1 = require("../controllers/user");
const auth_1 = require("../middlewares/auth");
const userRouter = (0, express_1.Router)();
userRouter.use(auth_1.protect);
userRouter.get('/', user_1.getUser);
userRouter.put('/', user_1.updateUser);
userRouter.delete('/', user_1.deleteUser);
exports.default = userRouter;
